# ----
# Site

title: Florex
url: "http://florex.com.ar/"
baseurl:
google_analytics_key:
google_maps_javascript_api_key:
snipcart_key: "NWNjOWZhYjctYmE1ZS00MDM3LThkNjUtZmE5M2NiMTU1NzAwNjM2MjYzNTE1MzM5ODg1ODkw"

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Florex -Envíos de flores a domicilio en Tucumán.
author:
  name: Florex
  email: ventas@Florex.com.ar
  twitter: florex
  phone: "+54 9381 533300"
social:
  name: Florex
  links:
    - https://florex.com.ar

# -----
# Build
timezone: Etc/UTC

collections:
  staff_members:
    _hide_content: true
  products:
    _hide_content: true
    output: true

permalink: pretty

defaults:
  -
    scope:
      path: ""
      type: "products"
    values:
      layout: "product"
  -
    scope:
      path: ""
    values:
      layout: "page"
  -
    scope:
      path: "index.html"
    values:
      layout: "default"

jekyll-archives:
  enabled:
    - categories

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

# -----------
# CloudCannon

garment_types:
  - hat
  - top

social_icons:
  - Email
  - Facebook
  - Google Plus
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - RSS

_comments:
  map: actualiza la locacion en el mapa..
  latitude: coordenadas para centrar el mapa.
  longitude: coordenadas para centrar el mapa.
  zoom: Zoom
  pricing_table: actualizar la tabla de precios.
  highlight: Poner emfasis en el texto
  color: Elfondo usado en nombre para llamar la acción.
  new_window: Abrir link en una nueva ventana
  description: enviar Flores en tucuman, florex, envio de rosas, enviar rosa, enviar ramo de rosas, comparar rosa, mandar flores, mandar una flor, manda una flor, manda una rosa
